# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://eandreas.github.io/covid19ana/"

git_url = "https://github.com/eandreas/covid19ana/tree/main/"

def custom_doc_links(name): return None
